# Generated by Django 4.2.10 on 2024-12-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='betaservis',
            name='our_friends',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='betaservistext',
            name='our_friends_text',
            field=models.TextField(default='test'),
        ),
    ]
