# Generated by Django 3.2.13 on 2024-12-11 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beta', '0002_betaservis_our_friends_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема вопроса')),
                ('email', models.EmailField(max_length=255, verbose_name='Ваша почта')),
                ('content', models.TextField(verbose_name='Ваш вопрос')),
                ('Time_create', models.DateTimeField(auto_now_add=True, verbose_name='Когда отправили')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP отправителя')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Гость')),
            ],
        ),
    ]
